server:
  port: 8080
spring:
  ## 数据库访问配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qr_code_riding?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 'zhu19940121'
    # 使用druid数据源
    druid:
      #最大连接池数量
      max-active: 50
      #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initial-size: 1
      min-idle: 1
      # 配置获取连接等待超时的时间
      max-wait: 10000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: false
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: 20
      #和上面的等价
      max-open-prepared-statements: 20
      #用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      validation-query: select 'x'
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.com.buu.dailyfresh.module.domain